about_us: <p> Nitro Agility is a Software House and IT Consulting business with offices in the United Kingdom and Europe. We were founded by a team of technology professionals that have experience working with leading companies across multiple sectors.</p><br/><p>Our team of highly skilled technologists help our clients to accelerate the delivery of technology platforms, whilst on-boarding cutting edge technology.</p>
why_us:
  - You can hire the right skills on demand
  - We can manage your project for you
  - Experience architecting cutting edge solutions
  - A distributed team ready for you
  - We do speak multiple languages
services:
  - title: Agile Delivery
    description: Feel connected and in control of your project riducing risk and time to delivery.
    image: images/services/agile-delivery.png
    alt_image: agile-delivery
    url:
  - title: Software Development
    description: We’ll build evolve and support your software solutions using either open source and off the shelf technology.
    image: images/services/software-development.png
    alt_image: software-development
    url:
  - title: Data Solutions
    description: We’ll help you to develop, deploy and manage big data infrastructure, environments and tooling 
    image: images/services/data-solutions.png
    alt_image: data-solutions
    url:
  - title: DevOps
    description: Let us help your teams to embrace automation, CI/CD and cutting edge tooling.
    image: images/services/devops.png
    alt_image: devops
    url:
  - title: Cloud Services
    description: Any journey to cloud-ready platforms can become a daunting task. We’ll advise and support you to implement the appropriate multi-cloud solutions. 
    image: images/services/cloud-services.png
    alt_image: cloud-services
    url:
  - title: Trainings
    description: Technical training forms a large part of our service, we have provided bespoke training solutions to many enterprise level clients.
    image: images/services/trainings.png
    alt_image: trainings
    url: