title: Bespoke Training tailored to your needs
content: <p>Many Companies support their employees personal and professional development, The demand to enhance and upgrade IT skills has never been higher. Around 85% of Technology professionals value learning and training above all other employment benefits. Employee retention is a huge challenge for all businesses, therefore a focus on developing your employee's skills is invaluable.</p></br></br><p>Next Generation Team provides access to experienced technical trainers who can provide both insightful and practical training sessions to your IT employees. Our portfolio of bespoke training services range from Language-specific Software Development workshops, through to innovation led training around concepts such as Blockchain and Data science.</p>
topics:
  - Architecture Patterns
  - Microservices Architectures
  - Cloud Devevelopment
  - Programming Languages (Python, JavaScript, Java, C#)
  - Database (Relational and NoSql)
  - Brokers (RabbitMQ, ActiveMQ, etc)
  - Apache (Kafka, Spark)
  - DevOps
  - Docker & Kubernetes
  - Activiy & BPMN
